"""Create drug table

Revision ID: 060324dddb61
Revises: bff5c5081290
Create Date: 2023-11-11 22:58:04.890049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060324dddb61'
down_revision: Union[str, None] = 'bff5c5081290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('leave_condition', sa.Enum('reception_yes', 'reception_no', name='condition'), nullable=False),
    sa.Column('release_form_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_form_id'], ['release_form.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drug')
    # ### end Alembic commands ###
