"""Added adress for manufacturer table

Revision ID: 378c964a738e
Revises: 060324dddb61
Create Date: 2023-11-12 18:34:10.852459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378c964a738e'
down_revision: Union[str, None] = '060324dddb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturer', sa.Column('adress', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufacturer', 'adress')
    # ### end Alembic commands ###
