"""Create migration: added column name for pharmacy table

Revision ID: f38f67bfa0ad
Revises: ac5038cb0b7a
Create Date: 2023-11-14 19:01:25.847881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38f67bfa0ad'
down_revision: Union[str, None] = 'ac5038cb0b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacy', 'name')
    # ### end Alembic commands ###
