"""Add cascade delete for available_in_pharmacy table

Revision ID: ac5038cb0b7a
Revises: d80d2d11f505
Create Date: 2023-11-14 00:01:12.637871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5038cb0b7a'
down_revision: Union[str, None] = 'd80d2d11f505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('available_in_pharmacy_availability_id_fkey', 'available_in_pharmacy', type_='foreignkey')
    op.drop_constraint('available_in_pharmacy_pharmacy_id_fkey', 'available_in_pharmacy', type_='foreignkey')
    op.create_foreign_key(None, 'available_in_pharmacy', 'pharmacy', ['pharmacy_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'available_in_pharmacy', 'availability', ['availability_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'available_in_pharmacy', type_='foreignkey')
    op.drop_constraint(None, 'available_in_pharmacy', type_='foreignkey')
    op.create_foreign_key('available_in_pharmacy_pharmacy_id_fkey', 'available_in_pharmacy', 'pharmacy', ['pharmacy_id'], ['id'])
    op.create_foreign_key('available_in_pharmacy_availability_id_fkey', 'available_in_pharmacy', 'availability', ['availability_id'], ['id'])
    # ### end Alembic commands ###
