version: '3.9'

services:
  rest_api_pharmacy:
    container_name: rest_api_pharmacy
    build: ..
    command: uvicorn --factory main:create_app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    volumes:
      - ../src:/usr/src/rest-api-pharmacy
      - ../.env:/usr/src/rest-api-pharmacy
    networks:
      - backend

networks:
  backend:
    driver: bridge