version: '3.9'

services:
  rest-api-pharmacy:
    container_name: rest_api_pharmacy
    build: ..
    command: uvicorn  src.main:create_app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    env_file:
      - ../.env
    volumes:
      - ..:/usr/src/rest-api-pharmacy/
    networks:
      - backend

networks:
  backend:
    driver: bridge