version: '3.9'
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - '5050:80'
    env_file:
      - ../.env
    networks:
      - backend

networks:
  backend:
    driver: bridge