version: '3.9'
services:
  postgres-pharmacy:
    image: postgres:alpine3.17
    container_name: db_postgres_pharmacy
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ../.env
    volumes:
      - postgres_data_pharmacy:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data_pharmacy:

networks:
  backend:
    driver: bridge