version: '3.9'
services:
  postgres_pharmacy:
    image: postgres:alpine3.17
    container_name: storage_pharmacy
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ../.env
    volumes:
      - postgres-pharmacy-db:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres-pharmacy-db:

networks:
  backend:
    driver: bridge